modulo03-desenvolvimento-web-com-python/20230709-aula10/alunos/urls.py
from django.urls import path

from . import views

app_name = "alunos"

urlpatterns = [
    path("perfil/", views.perfil, name="perfil"),
]

modulo03-desenvolvimento-web-com-python/20230709-aula10/escola_de_cursos/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('__debug__/', include('debug_toolbar.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('registro/', include('registro.urls')),
    path('alunos/', include('alunos.urls')),
    path('cursos/', include('cursos.urls')),
]

urlpatterns += [path('', RedirectView.as_view(url="/auth/login", permanent=True)),]

modulo03-desenvolvimento-web-com-python/20230709-aula10/registro/urls.py
from django.urls import path

from . import views

app_name = "registro"

urlpatterns = [
    path("pre/", views.pre_registro, name="pre_registro"),
    path("pre/<uuid>/reenviar", views.reenviar_pre_registro, name="reenviar_pre_registro"),
    path("confirmacao/", views.registrar, name="registrar"),
    path("processar-login/", views.processar_login, name="processar_login"),
]

modulo03-desenvolvimento-web-com-python/20230709-aula10/registro/models.py
from uuid import uuid4

from django.db import models


class PreRegistro(models.Model):

    email = models.EmailField("E-mail", max_length=200)
    uuid = models.UUIDField(default=uuid4)
    data_hora = models.DateTimeField(auto_now_add=True)
    valido = models.BooleanField(default=True)

    class Meta:
        db_table = "tb_pre_registro"

modulo03-desenvolvimento-web-com-python/20230709-aula10/registro/forms.py
from django import forms

class PreRegistroForm(forms.Form):
    email = forms.EmailField(required=True, label="E-mail", widget=forms.EmailInput(attrs={"class": "form-control", "placeholder": "Informe o seu E-mail"}))

modulo03-desenvolvimento-web-com-python/20230709-aula10/registro/views.py
from django.conf import settings
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.utils import timezone

from registro.forms import PreRegistroForm
from registro.models import PreRegistro
from registro.utils import enviar_email

from registro.validators import (
    dados_preenchidos, username_ou_email_ja_cadastrado, senha_valida
)

def registrar(request):

    if request.method == "GET":

        pre_registro = PreRegistro.objects.filter(uuid=request.GET.get("id")).first()

        error_message = None

        if not pre_registro:
            error_message = "Token de confirmação não encontrado!"

        elif not pre_registro.valido:
            error_message = "Token inválido."
    
        elif settings.PRE_REGISTRO_TIME_LIMIT < (timezone.now() - pre_registro.data_hora).total_seconds():
            error_message = "O Token expirou."
        
        if error_message:
            return render(
                request, "falha_confirmacao_pre_cadastro.html", {"error_message": error_message, "pre_registro": pre_registro}
            )

        return render(request, "registro.html", {"pre_registro": pre_registro})

    elif request.method == "POST":
        
        try:

            username = request.POST['username']
            email = request.POST['email']
            senha = request.POST['password1']
            confirmacao_senha = request.POST['password2']
            uuid_pre_registro = request.POST['uuid_pre_registro']

            error_message = None

            if not dados_preenchidos(username, email, senha, confirmacao_senha):
                error_message = "Todos os campos são obrigatórios"

            elif username_ou_email_ja_cadastrado(username, email):
                error_message = "Existe algum problema no seu cadastro"

            elif not senha_valida(senha, confirmacao_senha):
                error_message = "As senhas não conferem."

            if error_message:
                return render(request, 'registro.html', {'error_message': error_message})
            
            User.objects.create_user(
                username=username, email=email, password=senha
            )

            pre_registro = PreRegistro.objects.get(uuid=uuid_pre_registro)
            pre_registro.valido = False
            pre_registro.save()

            return redirect("login")

        except Exception:
            pass


def pre_registro(request):

    if request.method == "GET":
        form = PreRegistroForm()

        return render(request, "pre_registro.html", {"form": form})
    
    elif request.method == "POST":
        
        form = PreRegistroForm(request.POST)

        if form.is_valid():

            email = form.cleaned_data.get("email")
            
            email_ja_cadastrado = User.objects.filter(email=email)
            email_no_pre_cadastro = PreRegistro.objects.filter(email=email, valido=False)

            if email_ja_cadastrado or email_no_pre_cadastro:

                form.errors.update({
                    "Erro de Pré-cadastro": "O e-mail informado é inválido. Verifique se o e-mail já não está cadastrado ou faz parte do pré-cadastro."
                })

                return render(request, "pre_registro.html", {"form": form})


            pre_registro = PreRegistro(email=email)
            pre_registro.save()

            enviar_email(pre_registro)

            return render(request, "envio_pre_cadastro.html")


def reenviar_pre_registro(request, uuid):
    if request.method == "GET":
        pre_registro = PreRegistro.objects.get(uuid=uuid)
        pre_registro.valido = False
        pre_registro.save()

        pre_registro = PreRegistro(email=pre_registro.email)
        pre_registro.save()

        enviar_email(pre_registro)

        return render(request, "envio_pre_cadastro.html")


@login_required
def processar_login(request):
    usuario = request.user

    if usuario.groups.filter(name="alunos").exists():
        return redirect("alunos:perfil")

    else:
        return redirect("login")

modulo03-desenvolvimento-web-com-python/20230709-aula10/registro/templates/envio_pre_cadastro.html
{% extends 'base.html' %}

{% block content %}
    <div class="row d-flex justify-content-center">
        <div class="col-6">
            <div class="alert alert-info">
                <p>Uma mensagem foi enviada para o seu e-mail com um link de confirmação do cadastro. Verifique
                    a sua caixa de SPAM se o e-mail não chegar dentro de alguns minutos.
                </p>
            </div>
        </div>
    </div>

{% endblock content %}

modulo03-desenvolvimento-web-com-python/20230709-aula10/registro/templates/falha_confirmacao_pre_cadastro.html
{% extends 'base.html' %}

{% block content %}
    <div class="alert alert-warning">
        <div class="row">
            <div class="col text-center">
                {{ error_message }}
            </div>
        </div>
    
        <div class="row">
            <div class="col text-center">
                {% if pre_registro %}
                    Caso queira enviar novamente o e-mail de confirmação, <a href="{% url 'registro:reenviar_pre_registro' pre_registro.uuid %}">Clique aqui.</a>
        
                {% else %}
                    <a href="{% url 'registro:pre_registro' %}">Clique aqui</a> para refazer o pré-cadastro.
                    
                {% endif %}
            </div>
        </div>

    </div>
{% endblock content %}

modulo03-desenvolvimento-web-com-python/20230709-aula10/registro/templates/pre_registro.html
{% extends 'base.html' %}

{% block content %}
    <div class="row d-flex justify-content-center mt-3">
        {% if form.errors %}
            <div class="alert alert-warning alert-dismissible fade show" role="alert">
                {% for title, message in form.errors.items %}
                    {{ message }}
                {% endfor %}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Fechar"></button>
            </div>
        {% endif %}
        <div class="col-3">
            <form action="" method="POST">
                {% csrf_token %}
                <div class="form-floating mb-3">
                    {{ form.email }}
                    <label for="{{ form.email.id_for_label }}" class="form-label">E-mail</label>
                </div>
                <div>
                    <input type="submit" value="Enviar" class="btn btn-primary w-100">
                </div>
            </form>
        </div>
    </div>
{% endblock content %}

modulo03-desenvolvimento-web-com-python/20230709-aula10/registro/templates/registro.html
{% extends 'base.html' %}

{% block content %}
    <div class="row d-flex justify-content-center">
        {% if error_message %}
            <div class="alert alert-warning alert-dismissible fade show" role="alert">
                {{ error_message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Fechar"></button>
            </div>
        {% endif %}
        <div class="col-3">
            <form class="login-form mt-5 pt-5" action="{% url 'registro:registrar' %}" method="POST">
                {% csrf_token %}
                <div class="mb-3">
                    <input type="text" name="username" id="username" class="form-control" placeholder="Digite seu usuário" required>
                </div>
                <div class="mb-3">
                    <input type="email" name="email" id="email" class="form-control" value={{ pre_registro.email }}>
                </div>
                <div class="mb-3">
                    <input type="password" name="password1" id="password1" class="form-control" placeholder="Digite sua senha" required>
                </div>
                <div class="mb-3">
                    <input type="password" name="password2" id="password2" class="form-control" placeholder="Confirme a sua senha" required>
                </div>

                <input type="hidden" name="uuid_pre_registro" value={{ pre_registro.uuid }}>
                
                <div class="d-flex justify-content-center">
                    <button type="submit" class="btn btn-primary">Cadastrar</button>
                </div>
            </form>
        </div>
    </div>

{% endblock content %}