modulo03-desenvolvimento-web-com-python/20230709-aula10/alunos/urls.py
from django.urls import path

from . import views

app_name = "alunos"

urlpatterns = [
    path("perfil/", views.perfil, name="perfil"),
]

modulo03-desenvolvimento-web-com-python/20230709-aula10/escola_de_cursos/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('__debug__/', include('debug_toolbar.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('registro/', include('registro.urls')),
    path('alunos/', include('alunos.urls')),
    path('cursos/', include('cursos.urls')),
]

urlpatterns += [path('', RedirectView.as_view(url="/auth/login", permanent=True)),]

modulo03-desenvolvimento-web-com-python/20230709-aula10/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">

    <title>{% block title %}Escola de Cursos{% endblock title %}</title>
</head>
<body>
    <div class="container">

        {% if user.is_authenticated %}
            <nav class="navbar navbar-expand-lg bg-body-tertiary">
            <div class="container-fluid">
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'alunos:perfil' %}">Home</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="#">Cursos</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="#">Turmas</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">Sair</a>
                  </li>
                </ul>
              </div>
            </div>
          </nav>
        {% endif %}
        
        {% block content %}{% endblock content %}

    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
</body>
</html>