modulo03-desenvolvimento-web-com-python/20230521-aula04/enquetes/urls.py
from django.urls import path

# O ponto (.) significa que iremos importar o módulo views que se encontra no mesmo
# diretório que o módulo urls
from . import views

# namespace
app_name = "enquetes"

urlpatterns = [
    path("numero-da-sorte/", views.numero_da_sorte, name="numero_da_sorte"),
    path("", views.index, name="index"),
    path("<int:pergunta_id>/", views.detalhes, name="detalhes"),
    path("<int:pergunta_id>/resultados/", views.resultados, name="resultados"),
    path("<int:pergunta_id>/votar/", views.votar, name="votar"),
    path("estatisticas/", views.estatisticas, name="estatisticas"),
    path("<int:pergunta_id>/nova_mensagem/", views.nova_mensagem, name="nova_mensagem"),
]

modulo03-desenvolvimento-web-com-python/20230521-aula04/sistema/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("enquetes/", include("enquetes.urls")),
]

modulo03-desenvolvimento-web-com-python/20230521-aula04/enquetes/models.py
from django.db import models


class Pergunta(models.Model):

    texto = models.CharField(max_length=200)
    data_de_publicacao = models.DateTimeField("Data de publicação")


    # A classe Meta representa as configurações da model
    class Meta:
        db_table = "tb_perguntas"

    def __str__(self):
        return self.texto


class Opcao(models.Model):

    pergunta = models.ForeignKey(Pergunta, on_delete=models.CASCADE)
    texto = models.CharField(max_length=200)
    votos = models.IntegerField(default=0)

    class Meta:
        db_table = "tb_opcoes"

    def __str__(self) -> str:
        return self.texto

modulo03-desenvolvimento-web-com-python/20230521-aula04/mensagens/models.py
from django.db import models

from enquetes.models import Pergunta


class Mensagem(models.Model):

    email = models.CharField(max_length=100, null=True, blank=True)
    texto = models.TextField(null=False)
    data_hora = models.DateTimeField(auto_now_add=True)
    pergunta = models.ForeignKey(Pergunta, on_delete=models.CASCADE)

    def __str__(self) -> str:
        return self.texto

    class Meta:
        db_table = "tb_mensagens"

modulo03-desenvolvimento-web-com-python/20230521-aula04/enquetes/views.py
from random import randint

from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse

from enquetes.models import Pergunta, Opcao
from mensagens.models import Mensagem

# enquetes/numero-da-sorte
def numero_da_sorte(request):
    numero_da_sorte = randint(1, 60)

    return HttpResponse(numero_da_sorte)


def index(request):
    ultimas_cinco_perguntas = Pergunta.objects.order_by("-data_de_publicacao")[:5]
    
    contexto = {
        "ultimas_cinco_perguntas": ultimas_cinco_perguntas
    }

    return render(request=request, template_name="enquetes/index.html", context=contexto)

def detalhes(request, pergunta_id):
    # pk = primary key
    # A função get_object_or_404 faz a consulta pelo registro com a pk informada.
    # Se não encontrar, gera um erro 404 NOT FOUND
    pergunta = get_object_or_404(Pergunta, pk=pergunta_id)

    return render(request, "enquetes/detalhes.html", {"pergunta": pergunta})


def resultados(request, pergunta_id):
    pergunta = get_object_or_404(Pergunta, pk=pergunta_id)

    return render(request, "enquetes/resultados.html", {"pergunta": pergunta})


def votar(request, pergunta_id):
    
    pergunta = get_object_or_404(Pergunta, pk=pergunta_id)

    try:
        opcao_selecionada = pergunta.opcao_set.get(pk=request.POST["opcao"])

    except (KeyError, Opcao.DoesNotExist):
        return render(
            request,
            "enquetes/detalhes.html",
            {
                "pergunta": pergunta,
                "mensagem_erro": "Você não escolheu uma opção válida!"
            }
        )

    else:
        opcao_selecionada.votos += 1
        opcao_selecionada.save()

        return HttpResponseRedirect(reverse("enquetes:resultados", args=(pergunta.id,)))


def estatisticas(request):

    qtd_perguntas = Pergunta.objects.count()
    qtd_opcoes = len(Opcao.objects.all())

    # Criar uma variável que vai armazenar a lista com as 3 perguntas com mais respostas
    # Dica: Use o método annotate (e chatgpt pra tirar duvidas)

    contexto = {
        "qtd_perguntas": qtd_perguntas,
        "qtd_opcoes": qtd_opcoes
    }

    return render(request, "enquetes/estatisticas.html", contexto)


def nova_mensagem(request, pergunta_id):

    if request.method == "GET":
        pergunta = get_object_or_404(Pergunta, pk=pergunta_id)

        return render(request, "enquetes/nova_mensagem.html", {"pergunta": pergunta})
    
    elif request.method == "POST":

        email = request.POST.get("email")
        texto = request.POST.get("texto")
        pergunta = get_object_or_404(Pergunta, pk=pergunta_id)

        nova_mensagem = Mensagem(
            email=email, texto=texto, pergunta=pergunta
        )

        nova_mensagem.save()

        return HttpResponseRedirect(reverse("enquetes:resultados", args=(pergunta.id,)))

modulo03-desenvolvimento-web-com-python/20230521-aula04/enquetes/templates/enquetes/detalhes.html
<form action="{% url 'enquetes:votar' pergunta.id %}" method="POST">
    {% comment %} Sempre colocar o built-in csrf_token quando estivermos trabalhando com envio de dados por formulário {% endcomment %}
    {% csrf_token %}

    <fieldset>
        <legend><h1>{{ pergunta.texto }}</h1></legend>
        {% if mensagem_erro %}
            <p><strong>{{ mensagem_erro }}</strong></p>
        {% endif %}

        {% for opcao in pergunta.opcao_set.all %}
            <input type="radio" name="opcao" id="opcao{{ forloop.counter }}" value="{{ opcao.id }}">
            <label for="opcao{{ forloop.counter }}">{{ opcao.texto }}</label><br />
        {% endfor %}

    </fieldset>

    <br /><input type="submit" value="Votar">

</form>

<hr />
<a href="{% url 'enquetes:index' %}">Voltar para a página principal</a>

modulo03-desenvolvimento-web-com-python/20230521-aula04/enquetes/templates/enquetes/estatisticas.html
<h2>Estatísticas do sistema de enquetes</h2>
<hr />

<p>Quantidade de Perguntas cadastradas: <strong>{{ qtd_perguntas }}</strong></p>
<p>Quantidade de Opções cadastradas: <strong>{{ qtd_opcoes }}</strong></p>
<p>As 3 perguntas com mais respostas:</p>
<ul>
    <li>Qual o seu programa de TV favorito? (3 votos)</li>
    <li>Qual o seu jogo de videogame favorito (1 voto)</li>
    <li></li>
</ul>

<hr />
<a href="{% url "enquetes:index" %}">Voltar para a página principal</a>

modulo03-desenvolvimento-web-com-python/20230521-aula04/enquetes/templates/enquetes/index.html
{% if ultimas_cinco_perguntas %}
    <ul>
        {% for pergunta in ultimas_cinco_perguntas %}
            <li><a href="{% url 'enquetes:detalhes' pergunta.id %}">{{ pergunta.texto }}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <p>Não existem perguntas cadastradas</p>
{% endif %}

<hr />

<a href="{% url 'enquetes:estatisticas' %}">Estatísticas do sistema</a>

modulo03-desenvolvimento-web-com-python/20230521-aula04/enquetes/templates/enquetes/nova_mensagem.html
<form action="{% url 'enquetes:nova_mensagem' pergunta.id %}" method="post">

    {% csrf_token %}

    <label for="email">E-mail</label>
    <input type="email" name="email" id="email">
    <br /><br />
    <label for="texto"><strong>Texto da mensagem</strong></label><br>
    <textarea name="texto" id="texto" cols="30" rows="10" required></textarea><br>

    <input type="submit" value="Enviar">
</form>

modulo03-desenvolvimento-web-com-python/20230521-aula04/enquetes/templates/enquetes/resultados.html
<h1>{{ pergunta.texto }}</h1>

<ul>
    {% for opcao in pergunta.opcao_set.all %}
        <li>{{ opcao.texto }} -- {{ opcao.votos }} voto{{ opcao.votos|pluralize }}.</li>
    {% endfor %}
</ul>

<hr />

<a href="{% url 'enquetes:detalhes' pergunta.id %}">Votar novamente?</a>
<a href="{% url 'enquetes:nova_mensagem' pergunta.id %}">Inserir comentário</a>

<hr />

{% if pergunta.mensagem_set.all %}
    {% for mensagem in pergunta.mensagem_set.all %}
        <div style="background-color: #c7c4bb;">
            <p>Email: <strong>{% if mensagem.email %}{{ mensagem.email }}{% else %}<i>Anônimo</i>{% endif %}</strong></p>
            <p>Mensagem: <strong>{{ mensagem.texto }}</strong></p>
            <p>Data/Hora: <strong>{{ mensagem.data_hora | date:"d/m/Y H:i:s" }}</strong></p>
        </div>
    {% endfor %}
{% else %}
    <p>Não há mensagens cadastradas para essa pergunta.</p>
{% endif %}