modulo03-desenvolvimento-web-com-python/20230709-aula10/alunos/urls.py
from django.urls import path

from . import views

app_name = "alunos"

urlpatterns = [
    path("perfil/", views.perfil, name="perfil"),
]

modulo03-desenvolvimento-web-com-python/20230709-aula10/cursos/urls.py
from django.urls import path

from . import views

app_name = "cursos"

urlpatterns = [
    path("", views.mostrar_todos_cursos, name="todos_os_cursos"),
    path("<int:curso_id>/", views.detalhe_do_curso, name="detalhe_do_curso"),
]

modulo03-desenvolvimento-web-com-python/20230709-aula10/escola_de_cursos/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('__debug__/', include('debug_toolbar.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('registro/', include('registro.urls')),
    path('alunos/', include('alunos.urls')),
    path('cursos/', include('cursos.urls')),
]

urlpatterns += [path('', RedirectView.as_view(url="/auth/login", permanent=True)),]

modulo03-desenvolvimento-web-com-python/20230709-aula10/alunos/models.py
from django.db import models

# Create your models here.

modulo03-desenvolvimento-web-com-python/20230709-aula10/alunos/views.py
from django.shortcuts import render

def perfil(request):

    lista_de_turmas_que_esta_matriculado = request.user.aluno.all()
    
    return render(
        request,
        "perfil.html",
        {"lista_de_turmas_que_esta_matriculado": lista_de_turmas_que_esta_matriculado}
    )

modulo03-desenvolvimento-web-com-python/20230709-aula10/alunos/templates/perfil.html
{% extends 'base.html' %}

{% block content %}

    {% if lista_de_turmas_que_esta_matriculado %}

        <h2 class="text-center">Lista de cursos que você está matriculado</h2>
    
        {% for turma in lista_de_turmas_que_esta_matriculado %}
            <div class="card mb-2" style="width: 30rem;">
                <div class="card-body">
                <h5 class="card-title">{{ turma.curso }}</h5>
                <h6 class="card-subtitle mb-2 text-body-secondary">
                    Curso ministrado por <strong>{{ turma.instrutor.first_name }} {{ turma.instrutor.last_name }}</strong>
                </h6>
                <p class="card-text">{{ turma.curso.descricao }}</p>
                <a href="#" class="card-link">Mais informações</a>
                </div>
            </div>
        {% endfor %}

    {% else %}
        <h3>Você ainda não se matriculou em nenhum curso. <a href="{% url 'cursos:todos_os_cursos' %}">Clique aqui</a> e garanta já a sua matrícula</h3>

    {% endif %}


{% endblock content %}